// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// svpCpp
List svpCpp(arma::vec u, int p, int J, bool trunc_lev, double del, int rho_type, bool wDecay);
RcppExport SEXP _wARMASVp_svpCpp(SEXP uSEXP, SEXP pSEXP, SEXP JSEXP, SEXP trunc_levSEXP, SEXP delSEXP, SEXP rho_typeSEXP, SEXP wDecaySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type u(uSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type J(JSEXP);
    Rcpp::traits::input_parameter< bool >::type trunc_lev(trunc_levSEXP);
    Rcpp::traits::input_parameter< double >::type del(delSEXP);
    Rcpp::traits::input_parameter< int >::type rho_type(rho_typeSEXP);
    Rcpp::traits::input_parameter< bool >::type wDecay(wDecaySEXP);
    rcpp_result_gen = Rcpp::wrap(svpCpp(u, p, J, trunc_lev, del, rho_type, wDecay));
    return rcpp_result_gen;
END_RCPP
}
// svpCpp_nolev
List svpCpp_nolev(arma::vec u, int p, int J, double del, bool wDecay);
RcppExport SEXP _wARMASVp_svpCpp_nolev(SEXP uSEXP, SEXP pSEXP, SEXP JSEXP, SEXP delSEXP, SEXP wDecaySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type u(uSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type J(JSEXP);
    Rcpp::traits::input_parameter< double >::type del(delSEXP);
    Rcpp::traits::input_parameter< bool >::type wDecay(wDecaySEXP);
    rcpp_result_gen = Rcpp::wrap(svpCpp_nolev(u, p, J, del, wDecay));
    return rcpp_result_gen;
END_RCPP
}
// svpCpp_h_ahead
List svpCpp_h_ahead(arma::vec u, int p, int J, int h, double del, bool wDecay);
RcppExport SEXP _wARMASVp_svpCpp_h_ahead(SEXP uSEXP, SEXP pSEXP, SEXP JSEXP, SEXP hSEXP, SEXP delSEXP, SEXP wDecaySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type u(uSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type J(JSEXP);
    Rcpp::traits::input_parameter< int >::type h(hSEXP);
    Rcpp::traits::input_parameter< double >::type del(delSEXP);
    Rcpp::traits::input_parameter< bool >::type wDecay(wDecaySEXP);
    rcpp_result_gen = Rcpp::wrap(svpCpp_h_ahead(u, p, J, h, del, wDecay));
    return rcpp_result_gen;
END_RCPP
}
// sim_svp_norm_cpp
arma::mat sim_svp_norm_cpp(arma::vec beta, int p, int N, int burnin);
RcppExport SEXP _wARMASVp_sim_svp_norm_cpp(SEXP betaSEXP, SEXP pSEXP, SEXP NSEXP, SEXP burninSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type burnin(burninSEXP);
    rcpp_result_gen = Rcpp::wrap(sim_svp_norm_cpp(beta, p, N, burnin));
    return rcpp_result_gen;
END_RCPP
}
// sim_svp_leverage_norm_cpp
List sim_svp_leverage_norm_cpp(arma::vec beta, int p, int N, int burnin);
RcppExport SEXP _wARMASVp_sim_svp_leverage_norm_cpp(SEXP betaSEXP, SEXP pSEXP, SEXP NSEXP, SEXP burninSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type burnin(burninSEXP);
    rcpp_result_gen = Rcpp::wrap(sim_svp_leverage_norm_cpp(beta, p, N, burnin));
    return rcpp_result_gen;
END_RCPP
}
// sim_sv_t_cpp
arma::mat sim_sv_t_cpp(arma::vec beta, int p, int N, int K, int burnin);
RcppExport SEXP _wARMASVp_sim_sv_t_cpp(SEXP betaSEXP, SEXP pSEXP, SEXP NSEXP, SEXP KSEXP, SEXP burninSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type burnin(burninSEXP);
    rcpp_result_gen = Rcpp::wrap(sim_sv_t_cpp(beta, p, N, K, burnin));
    return rcpp_result_gen;
END_RCPP
}
// sim_sv_ged_cpp
arma::mat sim_sv_ged_cpp(arma::vec beta, int p, int N, int K, int burnin);
RcppExport SEXP _wARMASVp_sim_sv_ged_cpp(SEXP betaSEXP, SEXP pSEXP, SEXP NSEXP, SEXP KSEXP, SEXP burninSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type burnin(burninSEXP);
    rcpp_result_gen = Rcpp::wrap(sim_sv_ged_cpp(beta, p, N, K, burnin));
    return rcpp_result_gen;
END_RCPP
}
// statPhi_cpp
arma::mat statPhi_cpp(arma::mat phiB);
RcppExport SEXP _wARMASVp_statPhi_cpp(SEXP phiBSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type phiB(phiBSEXP);
    rcpp_result_gen = Rcpp::wrap(statPhi_cpp(phiB));
    return rcpp_result_gen;
END_RCPP
}
// kendall_corr
double kendall_corr(arma::vec x, arma::vec y);
RcppExport SEXP _wARMASVp_kendall_corr(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(kendall_corr(x, y));
    return rcpp_result_gen;
END_RCPP
}
// acov_g
arma::mat acov_g(arma::mat y, int k);
RcppExport SEXP _wARMASVp_acov_g(SEXP ySEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(acov_g(y, k));
    return rcpp_result_gen;
END_RCPP
}
// acov_symmetric
arma::mat acov_symmetric(arma::mat y, int k);
RcppExport SEXP _wARMASVp_acov_symmetric(SEXP ySEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(acov_symmetric(y, k));
    return rcpp_result_gen;
END_RCPP
}
// signR_cpp
arma::cx_vec signR_cpp(arma::cx_vec vec);
RcppExport SEXP _wARMASVp_signR_cpp(SEXP vecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cx_vec >::type vec(vecSEXP);
    rcpp_result_gen = Rcpp::wrap(signR_cpp(vec));
    return rcpp_result_gen;
END_RCPP
}
// rged_cpp
arma::vec rged_cpp(int n, double mean, double sd, double nu);
RcppExport SEXP _wARMASVp_rged_cpp(SEXP nSEXP, SEXP meanSEXP, SEXP sdSEXP, SEXP nuSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< double >::type sd(sdSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    rcpp_result_gen = Rcpp::wrap(rged_cpp(n, mean, sd, nu));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_wARMASVp_svpCpp", (DL_FUNC) &_wARMASVp_svpCpp, 7},
    {"_wARMASVp_svpCpp_nolev", (DL_FUNC) &_wARMASVp_svpCpp_nolev, 5},
    {"_wARMASVp_svpCpp_h_ahead", (DL_FUNC) &_wARMASVp_svpCpp_h_ahead, 6},
    {"_wARMASVp_sim_svp_norm_cpp", (DL_FUNC) &_wARMASVp_sim_svp_norm_cpp, 4},
    {"_wARMASVp_sim_svp_leverage_norm_cpp", (DL_FUNC) &_wARMASVp_sim_svp_leverage_norm_cpp, 4},
    {"_wARMASVp_sim_sv_t_cpp", (DL_FUNC) &_wARMASVp_sim_sv_t_cpp, 5},
    {"_wARMASVp_sim_sv_ged_cpp", (DL_FUNC) &_wARMASVp_sim_sv_ged_cpp, 5},
    {"_wARMASVp_statPhi_cpp", (DL_FUNC) &_wARMASVp_statPhi_cpp, 1},
    {"_wARMASVp_kendall_corr", (DL_FUNC) &_wARMASVp_kendall_corr, 2},
    {"_wARMASVp_acov_g", (DL_FUNC) &_wARMASVp_acov_g, 2},
    {"_wARMASVp_acov_symmetric", (DL_FUNC) &_wARMASVp_acov_symmetric, 2},
    {"_wARMASVp_signR_cpp", (DL_FUNC) &_wARMASVp_signR_cpp, 1},
    {"_wARMASVp_rged_cpp", (DL_FUNC) &_wARMASVp_rged_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_wARMASVp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
