# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

svpCpp <- function(u, p, J, trunc_lev, del, rho_type = 1L, wDecay = FALSE) {
    .Call(`_wARMASVp_svpCpp`, u, p, J, trunc_lev, del, rho_type, wDecay)
}

svpCpp_nolev <- function(u, p, J, del, wDecay = FALSE) {
    .Call(`_wARMASVp_svpCpp_nolev`, u, p, J, del, wDecay)
}

svpCpp_h_ahead <- function(u, p, J, h, del, wDecay = FALSE) {
    .Call(`_wARMASVp_svpCpp_h_ahead`, u, p, J, h, del, wDecay)
}

sim_svp_norm_cpp <- function(beta, p, N, burnin) {
    .Call(`_wARMASVp_sim_svp_norm_cpp`, beta, p, N, burnin)
}

sim_svp_leverage_norm_cpp <- function(beta, p, N, burnin) {
    .Call(`_wARMASVp_sim_svp_leverage_norm_cpp`, beta, p, N, burnin)
}

sim_sv_t_cpp <- function(beta, p, N, K, burnin) {
    .Call(`_wARMASVp_sim_sv_t_cpp`, beta, p, N, K, burnin)
}

sim_sv_ged_cpp <- function(beta, p, N, K, burnin) {
    .Call(`_wARMASVp_sim_sv_ged_cpp`, beta, p, N, K, burnin)
}

statPhi_cpp <- function(phiB) {
    .Call(`_wARMASVp_statPhi_cpp`, phiB)
}

kendall_corr <- function(x, y) {
    .Call(`_wARMASVp_kendall_corr`, x, y)
}

acov_g <- function(y, k) {
    .Call(`_wARMASVp_acov_g`, y, k)
}

acov_symmetric <- function(y, k) {
    .Call(`_wARMASVp_acov_symmetric`, y, k)
}

signR_cpp <- function(vec) {
    .Call(`_wARMASVp_signR_cpp`, vec)
}

rged_cpp <- function(n, mean = 0.0, sd = 1.0, nu = 2.0) {
    .Call(`_wARMASVp_rged_cpp`, n, mean, sd, nu)
}

